name: test
on: [push, pull_request]

jobs:
  build:
    runs-on: macos-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v6

    - name: Setup Python
      uses: actions/setup-python@v6
      with:
        python-version: '3.10.4'

    - name: Setup tmate session
      uses: mxschmitt/action-tmate@v3

    - name: test
      shell: bash -el {0}
      run: |
        exit 1
